### ISSUE TITLE
Redeploy on Heroku

### ISSUE THREAD

**Issue by leestanley** [acmucsd/membership-portal-ui#131]

**Comment by ronakdev** [comment]
Why do we want to do this? Netlify is free atm; heroku might cost more, and right now it seems UI doesn't need additional features?

**Comment by leestanley** [comment]
> Why do we want to do this? Netlify is free atm; heroku might cost more, and right now it seems UI doesn't need additional features?

Netlify isn't the best for teams - if someone wants to add env variables then I have to do it myself. Unless we buy the team package (can we get a netlify sponsorship LOL) its not good for orgs. https://www.netlify.com/pricing/#teams

**Comment by ronakdev** [comment]
Oh that's totally fair; completely forgot about env vars lol (i'll look into asking netlify) but yeah nvm lmao ty for reminding me

**Comment by leestanley** [comment]
> Oh that's totally fair; completely forgot about env vars lol (i'll look into asking netlify) but yeah nvm lmao ty for reminding me

An alternative solution would be using the acm email to build the project

**Comment by sumeet-bansal** [comment]
We also have payment set up on Heroku, so we can put the front end on a hobby dyno since it was the bottleneck during the Fall Kickoff event. We'll still use Netlify for development since it's great for that, but we'll be using Heroku for production.
