### ISSUE TITLE
NavProfile Image Icon+Progress Ring Position off for Firefox

### ISSUE THREAD

**Issue by annsudhart** [acmucsd/membership-portal-ui#218]
The avatar icon and the progress ring is separated. It's still functional though, it just covers the name and looks off.

![image](https://user-images.githubusercontent.com/32887362/81014206-4f0c0f00-8e11-11ea-859c-5bf6cf5f43f0.png)

**Comment by steets250** [comment]
Profile image is over to the right for some reason. The other elements line up correctly.
