### ISSUE TITLE
Event Card: Events are in Past Prematurely

### ISSUE THREAD

**Issue by steets250** [acmucsd/membership-portal-ui#248]
<img width="304" alt="Screen Shot 2020-05-06 at 5 44 52 PM" src="https://user-images.githubusercontent.com/5706163/81242234-71dd2580-8fc1-11ea-87b1-01bc926b463d.png">

This event has not yet occurred and is in the past events category.

**Comment by sumeet-bansal** [comment]
This is a backend issue.
