### ISSUE TITLE
Password Reset: No Buttons

### ISSUE THREAD

**Issue by steets250** [acmucsd/membership-portal-ui#270]
There should be some sort of "Enter" button on this screen. Right now the only way to submit is to hit enter.

<img width="758" alt="Screen Shot 2020-05-11 at 12 03 15 AM" src="https://user-images.githubusercontent.com/5706163/81533343-e1814680-931a-11ea-9ff2-b0d601cc144f.png">

**Comment by leestanley** [comment]
oops i made that
