### ISSUE TITLE
Navbar: Mini Portal Redesign

### ISSUE THREAD

**Issue by leestanley** [acmucsd/membership-portal-ui#343]
![image.png](https://images.zenhubusercontent.com/5ef95b171b65564a5748eadb/85d679d1-f274-44f0-a40b-5b79069c92e4)

**Comment by steets250** [comment]
When you redo the header, can you conditionally add the mobile drop-down menu only when the user is both logged in and on mobile? The navbar is now also used both when the user is and isn't logged in, so we want to only show the nav menu when they're authenticated.
