### ISSUE TITLE
Leaderboard Page: Add time-based window, increase loading count

### ISSUE THREAD

**Issue by leestanley** [acmucsd/membership-portal-ui#384]
- [ ] Started at end of school year, e.g. 2019-2020 school year = June 15th 2019 - > June 15th 2020
- [x] Increase loading count to 100

**Comment by annsudhart** [comment]
@leestanley The current Figma design shows different timeframes by quarter, are we just doing 
- 2020-2021 school year (9/21/20-Current)
- 2019-2020 school year (6/15/19-6/15/20)
- All Time?

![image](https://user-images.githubusercontent.com/32887362/97659965-91638100-1a2d-11eb-886a-09d37c210e93.png)

**Comment by leestanley** [comment]
> @leestanley The current Figma design shows different timeframes by quarter, are we just doing
> 
> * 2020-2021 school year (9/21/20-Current)
> * 2019-2020 school year (6/15/19-6/15/20)
> * All Time?
> 
> ![image](https://user-images.githubusercontent.com/32887362/97659965-91638100-1a2d-11eb-886a-09d37c210e93.png)

Prefer the new redesign with a dropdown

![image](https://user-images.githubusercontent.com/8893880/97660471-e8b62100-1a2e-11eb-9793-afd510e81723.png)
