### ISSUE TITLE
Profile Picture state not updated locally after editing

### ISSUE THREAD

**Issue by ivychxn** [acmucsd/membership-portal-ui#412]
sad :(

**Comment by StormFireFox1** [comment]
@shravanhariharan2 make sure to check if the backend can support profile changing. Maybe the AWS URL change messed some stuff up in here?

**Comment by StormFireFox1** [comment]
Found the bug, seems to be a local state issue with the profile picture.

This was apparently @steets250's issue, so we can call off the backend gods on this one.

**Comment by steets250** [comment]
Duplicate of #198 , my very first interaction with the portal repo 🥺
