### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by trulyronak** [acmucsd/membership-portal-ui#503]
I think this is a be related issue, but @shravanhariharan2 @steets250 can confirm.

Currently, for all `PublicOrderItem`s, we don't have
- an item name (so we use the uuid rn)
- a correct quantity (it always seems to be -1 in `item.option.quantity`)
- a user name (so we use the user uuid rn)

**Comment by shravanhariharan2** [comment]
For 1 and 3, you can use the respective API routes (GET /merch/item/:uuid and GET /user/:uuid) to get those fields (we aren't using redundancy in the backend so those values only exist on the `MerchItem` and `User` entities, respectively), and for 2, we shouldn't be using the `option.quantity` field for counting items that were ordered. We want to instead count the number of `PublicOrderItems` that exist for the same option for a given order. e.g. if I order 3 small T-shirts, there will be 3 separate `PublicOrderItem` objects that have `option: <small-t-shirt-uuid>`. `option.quantity` is used for keeping track of stock for a given item's option.

**Comment by steets250** [comment]
These are present on `AdminFulfillPage`, `OrdersPage`, and `OrderPage`.

**Comment by StormFireFox1** [comment]
Fixed.
