### ISSUE TITLE
Store Not Deployed

### ISSUE THREAD

**Issue by StormFireFox1** [acmucsd/membership-portal-ui#519]
Netlify reports deploys locked to previous commit. Unlock deploys after store assets loaded.

**Comment by steets250** [comment]
👺

**Comment by nishantbalaji** [comment]
January 10, 2022. 9:17 PM PST. Store is still not deployed. Will it ever come? Will it ever happen?

**Comment by StormFireFox1** [comment]
Store deployed

**Comment by nishantbalaji** [comment]
January 10, 2022. 9:25 PM PST. It's still not out. Why are we here? Just to suffer?

**Comment by nishantbalaji** [comment]
January 10, 2022. 9:32 PM PST. I hear it coming. It must be happening soon. It has to be.

**Comment by trulyronak** [comment]
@nishantbalaji thank you for your patience. At this time, all of our operators are busy with other users. We promise we'll get back to you soon

**Comment by TristanTjan** [comment]
Wow such a responsive team, but still no store

**Comment by trulyronak** [comment]
@TristanTjan thank you for your patience. At this time, all of our operators are busy with other users. We promise we'll get back to you soon.

**Comment by nishantbalaji** [comment]
January 10, 2022. 9:36 PM PST. It's got to be today. I just want to buy my ACM™ branded merchandise.

**Comment by trulyronak** [comment]
@nishantbalaji thank you for your patience. At this time, all of our operators are busy with other users. We promise we'll get back to you soon

**Comment by nishantbalaji** [comment]
> Wow such a responsive team, but still no store

Seems that they have their priorities backwards. Seems _too_ responsive for someone who should be working on store.

**Comment by TristanTjan** [comment]
> > Wow such a responsive team, but still no store
> 
> Seems that they have their priorities backwards. Seems _too_ responsive for someone who should be working on store.

I know seems like bad resource allocation

**Comment by trulyronak** [comment]
@TristanTjan @nishantbalaji thank you for your patience. At this time, all of our operators are busy with other users. We promise we'll get back to you soon

**Comment by TristanTjan** [comment]
Dang these automated bots are just as bad as on twitter

**Comment by nishantbalaji** [comment]
January 10, 2022. 10:00 PM PST. It has happened. Store is upon us! All is well.

**Comment by steets250** [comment]
See ya

**Comment by trulyronak** [comment]
@TristanTjan @nishantbalaji i told you so smh the store is upon us and we must praise its glory, all hail the store
