### ISSUE TITLE
Inconsistent padding on Board Pictures organization selection buttons

### ISSUE THREAD

**Issue by alistairgray42** [acmucsd/membership-portal-ui#546]
![image](https://user-images.githubusercontent.com/28539155/156505865-75a5cc27-44e9-4c50-b509-8344bc6b2700.png)

e.g. the horizontal padding on the "hack" button is smaller than for "ai"

**Comment by steets250** [comment]
@alistairgray42 thanks for submitting, can you open the issue on the https://github.com/acmucsd/main-website repo? That's where the main website code is worked on.

**Comment by trulyronak** [comment]
replicated the issue on main-website, closing it here
