### ISSUE TITLE
Make QR Code Check-in Smoother

### ISSUE THREAD

**Issue by farisashai** [acmucsd/membership-portal-ui#581]
QR Code url checkins currently only work as expected when you're already logged in to receive points for the event.

Example: 
https://members.acmucsd.com/checkin?code=resumereviewz

When a user goes to the checkin URL and has to log in first, they don't get checked in to the event. We should be able to save this as a pending state until the checkin can successfully be applied to their account so they don't have to do it again or type the checkin code manually to create a smoother user experience.

**Comment by steets250** [comment]
Hmm this used to work, I wonder if something relating to the Redux cleanup broke the pending code being passed in.

**Comment by farisashai** [comment]
Hm we'll need to test to reproduce exact steps later but I know Shirley and other people have been running into issues during events.
