### ISSUE TITLE
Implement auth in frontend

### ISSUE THREAD

**Issue by ClarkPhan** [acmucsd/membership-portal-ui#76]
client will store jwt (in cookie) that will be used for requests to server

**Comment by ClarkPhan** [comment]
> 
> 
> have you thought about how're you including the JWT in the request?

maybe something like this:
***************************
import jwt from 'jsonwebtoken';
// function that is called when user is logged in
// we can get user object from db or something
jwt.sign({user}, 'privatekey', { expiresIn: '1h' }, (err, token) => {
  if(err) { console.log(err) }    
  document.cookie = token;
});
***************************
using: 
1. https://www.npmjs.com/package/jsonwebtoken
2. https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie

**Comment by sumeet-bansal** [comment]
The JWT is signed by the server, so all you need to do is call the API route for login, store the token in the response, and send it in each request.

**Comment by eminguyen** [comment]
@ClarkPhan what's the update on this, did you decide how you want to store it? From what I've read online, it's best to just use httpOnly cookies. I think local storage is insecure. Do you want me to look into implementing this tomorrow?

**Comment by ClarkPhan** [comment]
I'm still waiting for you to send me the .env file

**Comment by sumeet-bansal** [comment]
@ClarkPhan is the client still going to send requests with an `Authorization` header?

**Comment by ClarkPhan** [comment]
> 
> 
> @ClarkPhan is the client still going to send requests with an `Authorization` header?

Yes, for jwt, we should use an authorization header
