### ISSUE TITLE
Add ESLinting

### ISSUE THREAD

**Issue by trulyronak** [acmucsd/membership-portal-ui#92]
## Why

We can solve coding bugs that can lead to problems not easily checked by us, and we can combine it with prettier to ensure proper code styling

## How

Use [Airbnb's ESLint config](https://github.com/airbnb/javascript) and make sure it works with prettier.

## Note

We should NOT enforce eslint for now since we're in crunch time, but after the portal ships we should prohibit code from being pushed without passing eslint (as a commit config / or push hook or something)

**Comment by leestanley** [comment]
haha 😢

**Comment by steets250** [comment]
haha 😁
